### ISSUE TITLE
FE: User tracking

### ISSUE THREAD

**Issue by willob99** [cs130-w21/18#33]
## User Story
As a **user**, I would like **to be able to log in, stay logged in, and log out** so that **I can move around the site and see my moods and playlists**.

## Detailed Description
We can keep track of the user as they move around the website with cookies. We also need to implement a login button and logout button.

## Acceptance Criteria
- [x] Given **a user is logged in**, then **their name appears on the page**
- [x] Given **a user is logged in**, then **there is a logout button on the page**
- [x] Given **a user is logged in**, then **clicking the logout button clears the user data from the page**
- [x] Given **no user is logged in**, then **a user can click the login button to log in with Spotify**
- [x] Given **the user is not logged in**, then **there is no user data on the page**
- [x] Given **the user is not logged in**, then **there is a login button on the home page**

**Comment by willob99** [comment]
Users can now log in with their Spotify account, stay logged in, and log out.
