### ISSUE TITLE
Build home page user interface

### ISSUE THREAD

**Issue by willob99** [cs130-w21/18#35]
## Epic
We need to implement a UI for the home page. The home page should:
* Provide a pleasant & welcoming landing page for the site
* Have a login button so users can log in with Spotify
* Show logged-in users their moods and playlists
* Let logged-in users see the playlists associated with each mood and have a link to the page for each playlist
* Have a link to the questionnaire page so logged-in users can create new moods
* Have a button for logged-in users to request new playlists from a certain mood
* Have a logout button
* Let the user switch between their personalized page (with their own moods/playlists) and an explore page (with other users' moods)

## User Stories
- [x] Build basic home page interface (issue #24)
- [x] Implement login/logout button and user tracking (issue #33)
- [ ] Add navigation to explore page (#85)
- [x] Implement home page API calls (issue #58, #62)
