### ISSUE TITLE
Data Persistence

### ISSUE THREAD

**Issue by keshpr** [cs130-w21/18#36]
## User Story
As a **User**, I would like **my created moods and playlists to be persistent** so that **I can listen to tracks on the fly without having to recreate playlists every time**.

## Detailed Description
Data such as a user's metadata, moods and playlists needs to be stored in a long lasting database to prevent loss of user information. The user should be able to create playlists in one session, logout, and access those same playlists in another session after login. 

## Acceptance Criteria
- [x] Given **a user creates a mood**, then **the mood is stored in a database**
- [x] Given **a user creates a playlist**, then **the playlist is stored in a database**
- [x] Given **a user logs in to our app**, then **their profile data such as Spotify refresh token is stored in a database**
