### ISSUE TITLE
Explore Page

### ISSUE THREAD

**Issue by sharvanijha** [cs130-w21/18#87]
## Epic
The user should be able to navigate to an Explore page from the Home page that lets them discover moods created by various users.

## User Stories
- [ ] The user ought to be able to access the explore page from the home page.
- [ ] The user should be able to view moods created by various users.
- [ ] The user should be able to save moods they are interested in.
- [ ] The user should be able to navigate back to the home page from the explore page.
